# -*- encoding: utf-8 -*-

import IU_CAMBIAR_NOMBRE_GRUPO
import IU_CREAR_GRUPO
import IU_CREAR_GRUPO_ANADIR_ALUMNO
import IU_CREAR_GRUPO_NOMBRE
import IU_GESTIONAR_SCRIPT
import IU_GESTIONAR_TAG
import IU_HISTORIAL
import IU_LOGIN
import IU_MAIN
import IU_MIS_TAGS
